//
//  SearchInteractor.swift
//  BookFinder
//
//  Created by Tophun on 2022/06/26.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    func search(request: Search.Search.Request)
}

protocol SearchDataStore {
    //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    var presenter: SearchPresentationLogic?
    var worker = SearchWorker()
    //var name: String = ""
    
    func search(request: Search.Search.Request) {
        presenter?.presentLoading()
        worker.search(query: request.query, startIndex: request.startIndex, maxResults: request.maxResults, completion: { [weak self] response in
            self?.presenter?.presentSearch(response: response)
        })
    }
}
