//
//  SearchRouter.swift
//  BookFinder
//
//  Created by Tophun on 2022/06/26.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func routeToDetail()
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    func routeToDetail() {
        guard let row = viewController!.tableView.indexPathForSelectedRow?.row,
              let previewLink = dataStore!.resultVolums[row].volumeInfo?.previewLink else { return }
        
        UIApplication.shared.open(URL(string: previewLink)!, options: [:], completionHandler: nil)
    }
}
