//
//  SearchModels.swift
//  BookFinder
//
//  Created by Tophun on 2022/06/26.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
    
    // MARK: Use cases
    enum Search {
        struct Request {
            var query: String
            var startIndex: Int
            var maxResults: Int
        }
        
        struct Response {
            var items: [Volume] = []
            var totalItems: Int = 0
            var error: Error?
        }
        
        struct ViewModel {
            struct ResultModel {
                var thumnailURL: String
                var title: String
                var author: String
                var publishedDate: String
            }
            
            var resultItems: [ResultModel]
            var totalItems: Int
        }
    }
}
